// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbL8hI-dI12hexPh5189zz6zJfkW_V-qw',
    appId: '1:66802086073:web:7bd01df87e2e1e34f36b68',
    messagingSenderId: '66802086073',
    projectId: 'food-app-e5b02',
    authDomain: 'food-app-e5b02.firebaseapp.com',
    storageBucket: 'food-app-e5b02.appspot.com',
    measurementId: 'G-4B7KZJWK6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxQ8IxaBzGD7UBNQ2Ne1Iac_nEP0TELFo',
    appId: '1:66802086073:android:6377860ad78d64e6f36b68',
    messagingSenderId: '66802086073',
    projectId: 'food-app-e5b02',
    storageBucket: 'food-app-e5b02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxhX1XLvDFVBxAjz3YSnz-sKoXvYasNsw',
    appId: '1:66802086073:ios:9cbe1f5f759b12b5f36b68',
    messagingSenderId: '66802086073',
    projectId: 'food-app-e5b02',
    storageBucket: 'food-app-e5b02.appspot.com',
    iosBundleId: 'com.example.foodDonation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxhX1XLvDFVBxAjz3YSnz-sKoXvYasNsw',
    appId: '1:66802086073:ios:9cbe1f5f759b12b5f36b68',
    messagingSenderId: '66802086073',
    projectId: 'food-app-e5b02',
    storageBucket: 'food-app-e5b02.appspot.com',
    iosBundleId: 'com.example.foodDonation',
  );
}
